### ISSUE TITLE
Slot is not align to the texture in GUIs

### ISSUE THREAD

**Issue by ShieLian** [LambdaInnovation/AcademyCraft#305]

**Comment by WeAthFoLD** [comment]
Provide the detailed list and slot please?

**Comment by ShieLian** [comment]
All the GUIs with Slots.

**Comment by WeAthFoLD** [comment]
Well, looks like slots are more or less distorted... But Minecraft Container takes only integer coordinates, and will not work out in CGUI because we use double and scale and much other stuff. I think this needs some support in CGUI to be able to **align slots to widget automatically**. In next release we can leave this be temporarily.

**Comment by Paindar** [comment]
Outdated issue without more information, close.
