### ISSUE TITLE
Suggestion: Psychokinetic class, or even telekinetic class?

### ISSUE THREAD

**Issue by HyperMan19680** [LambdaInnovation/AcademyCraft#323]
I will admit, I like what I am seeing so far as the skills, but I wonder if we can potentially see a way to move entities/items about with the mind. I can see one skill lifting a mob high into the sky, and then toss them down, doing fall damage.

And speaking of moving entities, will there be a way to teleport enties to different spots with the Teleporter class in the future?

**Comment by Renniuq** [comment]
Well, the location teleport ability will actually move (from what I've been able to tell) up to 4 additional entities near you along with you. This can be quite useful for deploying groups of players to certain areas in one swoop, or teleporting villagers from your MFR autospawner into your TConstruct Smeltery for Emeralds. But I would enjoy a method of solely moving other entities, and maybe to locations near you, rather than recorded ones.

**Comment by WeAthFoLD** [comment]
Currently our next move will not be add more categories but to fall back and refine current ones. There are lots of ideas can be incorporated for current skills to make them more useful. And yes, Teleporter could use some skill as @Renniuq said.

But in the long run the variety of categories will always do, I mean why not? Feel free to come up with your own design and view for the category, and it will definetly inspire us.

**Comment by WeAthFoLD** [comment]
Closed due to not being constructive.
