### ISSUE TITLE
[1.0.4] Data Terminal not working in Dimensions greater then 127

### ISSUE THREAD

**Issue by jabba87** [LambdaInnovation/AcademyCraft#504]
When you are in a Dimension with an id greater then 127 (and supposedly smaller then -127, but i didn't have a dimension to test) you are unable to open the terminal. ("You have not yet installed Data Terminal.")
If you are trying to install the Terminal again, it doesn't allow installation ("You have already installed Data Terminal.")

**Comment by WeAthFoLD** [comment]
Wow, this shed quite some light on this long-existing problem. Will test and get it fixed.

BTW, how large is the range of dimension IDs supposed to be? Is -32767~32768 sufficient?

// devnote below

I suppose this is because LambdaLib used byte in serializing `World`, which is used in serializing entities. When the byte overflows the instance can't be correctly fetched, and the synchronization function won't get called, causing inconsistency between client/server.

**Comment by johannes-wagner** [comment]
That range would be sufficient for our purposes. We assign a private dimension to each of our players, with the ids ranging in the mid thousands on the larger and older servers.

**Comment by jabba87** [comment]
Thank you for the quick answer.
That range would be sufficient for our purposes. We assign a private dimension to each of our players, with the ids ranging in the mid thousands on the larger and older servers.
(Posted with wrong account before)

**Comment by WeAthFoLD** [comment]
Fixed in next release.
