### ISSUE TITLE
[Bug?] Teleporter AC v1.0.6

### ISSUE THREAD

**Issue by Niconoko** [LambdaInnovation/AcademyCraft#544]
I think the teleporting blue? image is not disappear when teleported, even I disabled the ability.

**Comment by Paindar** [comment]
which image? I can't understand...

**Comment by Niconoko** [comment]
While player holding a teleporting skill, it creates a blue human shape image particle in front of the player, right? And once released and teleported, the blue human shape particle is still remain.

**Comment by Paindar** [comment]
Amazing. I have never seen such phenomenon.
Could you tell me your version of forge?

**Comment by Niconoko** [comment]
It's 10.13.4.1558-1.7.10

**Comment by Paindar** [comment]
Well....Normal if occasionally.
Or please provide more information to help us...

**Comment by Niconoko** [comment]
It's not crashing my game, so I don't know what am I going to provide here, but if the picture can say more than word, here are some of them...

![2016-12-21_05 58 49](https://cloud.githubusercontent.com/assets/24541618/21371472/2ba9da02-c744-11e6-9726-76f8d1aa62f0.png)
^ During ability activation

![2016-12-21_05 59 00](https://cloud.githubusercontent.com/assets/24541618/21371469/2ba8c18a-c744-11e6-9a3c-a85257afe00d.png)
^ About to use skill which is teleportation

![2016-12-21_05 59 11](https://cloud.githubusercontent.com/assets/24541618/21371468/2ba7bc18-c744-11e6-9ad6-35aee886fc57.png)
^ After teleported, the "blue human shape image particle" is still remain

![2016-12-21_05 59 20](https://cloud.githubusercontent.com/assets/24541618/21371467/2ba72cee-c744-11e6-9342-9189eecdef13.png)
^ Even I have deactivated the ability activation, the "blue human shape image particle" is still there

![2016-12-21_06 00 11](https://cloud.githubusercontent.com/assets/24541618/21371470/2ba99920-c744-11e6-832b-904ee8a4982e.png)
^ Just another view angle

![mod list](https://cloud.githubusercontent.com/assets/24541618/21371471/2ba9a0a0-c744-11e6-8c95-a8e03c05c7f6.png)
^ This is my mod list

**Comment by Paindar** [comment]
Fixed.

**Comment by bookdevourer** [comment]
I am currently experiencing this in AC v1.0.6. It didn't happen at first, and to the best of my recollection, I first noticed it after I had spammed Mark Teleport. Let me know if I can provide any other information that could help with solving this.

**Comment by Paindar** [comment]
It will happen if the cooldown is 0 tick, so there is nothing to do but wait for a new version :(

**Comment by bookdevourer** [comment]
Understood. Thanks for responding so quickly.

**Comment by Quiesdoe** [comment]
Haven't seen this one, so please ignore the pull request from me, if the bug is known.
I wish I could fix this myself, but I am not able to build the mod myself with my fix (preventing the 0 cooldown by changing ctx.setCooldown(lerpf(30, 0, exp).toInt to ctx.setCooldown(lerpf(30, 1, exp).toInt).
I'm getting the following two errors when I try to build:

AcademyCraft.git\build\sources\scala\cn\academy\core\client\ui\TechUI.scala:222: class ContainerUI needs to be abstract, since method drawGuiContainerBackgroundLayer in class GuiContainer of type (x$1: Float, x$2: Int, x$3: Int)Unit is not defined
  class ContainerUI(container: Container, pages: Page*) extends CGuiScreenContainer(container)

AcademyCraft.git\build\sources\scala\cn\academy\vanilla\electromaster\skill\MineDetect.scala:122: class HandlerEntity needs to be abstract, since method entityInit in class Entity of type ()Unit is not defined
class HandlerEntity(_target: EntityPlayer, _time: Int, _range: Double, _advanced: Boolean) extends EntityAdvanced(_target.worldObj)

Don't know what to do here since I'm not a Java developer :-/
