### ISSUE TITLE
[Question] Support for newer Minecraft version

### ISSUE THREAD

**Issue by C0rn3j** [LambdaInnovation/AcademyCraft#576]
Hi! I couldn't find this information anywhere -

This mod looks like tons of fun, but is still on the old 1.7.10 version. Are there plans to move to the older 1.10.2 or current 1.11.2 version?

I know this question is generally hated, but I really couldn't find an answer anywhere!

**Comment by Renniuq** [comment]
I'm thinking either they'll update it once they get this version all stable (and once they get more free time, seems progress has died down recently, so my best guess is real life happened. School, maybe?) or they'll just keep it at 1.7.10 since its likely 1.7.10 will remain a fairly widely-used version for a long time to come, since there are so many mods that sprang up in this version and that won't move on. I would personally prefer the former, since many of the mods on both versions are so much better in the later one (like Tinkers), but I fully respect its their mod and they can do whatever they wish with it. Also if they did what they didn't want with it, it would reduce quality, and cause other problems. Mods are generally products of love, not necessity, after all.

**Comment by Mastize** [comment]
@Renniuq  thank you for your comment! Basically you are right. I am going to talk about this problem on behalf of my team. 

In fact, after we accomplished two large minecraft mods (LambdaCraft and AcademyCraft), we felt that our team could make something much more fancy than merely minecraft mods, and we are really tired of keeping up with the pace of minecraft. So, main members of our team are focusing on the development of an indie game right now, and we won't have any huge update on this mod for a long period, at least several months.

I feel sorry about keeping you waiting.

**Comment by C0rn3j** [comment]
@Mastize Thanks a lot for taking the time to answer.

I wish you'll have success with your game and that you're going to return some time to update the mod ^^

I'd leave this issue open so people can find this easier

**Comment by WeAthFoLD** [comment]
We are now rebooting AcademyCraft's development now, and the most recent plan is to upgrade the mod to MC 1.12 (Which will take likely 1-2 months). Several content updates are planned after that. 😃
