### ISSUE TITLE
mod broken. pls fix

### ISSUE THREAD

**Issue by KanitoKawaii** [LambdaInnovation/AcademyCraft#583]
the normal and advanced developers don't render for me, they are there but they have no models or textures, also when i try to learn a power the simulation progress bar stays at 00 percent, i left it for over an hour and nothing happened, pls tell me what to do

**Comment by Renniuq** [comment]
A list of your mods (or what pack you dropped them into, if you did that) and the versions of LambdaLib and AcademyCraft would be helpful. Probably rename the issue to closer reflect the specific problem, something along the lines of "[mod version] Developers not rendering and simulation progress not increasing"

Also, since most of the team that worked on the mod have moved to another project, it'll probably take a while at best if the issue isn't simply compat with another mod, in which case you'd just need to pull said mod out. Just a fair warning.
