### ISSUE TITLE
[Issue] Jet Engine flying through blocks

### ISSUE THREAD

**Issue by DarianLStephens** [LambdaInnovation/AcademyCraft#607]
If you angle your destination just before it touches the roof, and fly at it, you'll go right through.
I made a video demonstrating this issue:
https://www.youtube.com/watch?v=2lpNTiGnAT8
Thank you for continuing development, and I hope to see this issue fixed, at least in the post-1.7.10 versions.

**Comment by Paindar** [comment]
We have noticed this problem, but after discussion we came to the conclusion that we need a better framework.
In other words, we are not going to deal with it immediately, but we will definitely deal with it in the next version in 1.12.2.
This problem is different from #609 , but our response is the same.

**Comment by Paindar** [comment]
Haven't still found this issue in 1.12.2 yet, close.
