### ISSUE TITLE
[Suggestion] Reset Fall Damage when finishing Jet Engine flight

### ISSUE THREAD

**Issue by DarianLStephens** [LambdaInnovation/AcademyCraft#608]
If you go for a flight in the skies with Jet Engine, you may be in for a rough landing, even if you go completely perpendicular to the ground for your approach.
The game will retain the total distance you've gone down, even if you cancel your momentum with Jet Engine before you hit the ground.
This is a shame, but maybe there's a reason for it being this way?

**Comment by Renniuq** [comment]
Its likely to do with how Minecraft calculates fall damage: Not based on how fast you hit the ground, but how far you have fallen. There was a similar issue with Magnet movement back in #284 and I've had to deal with the same issue when making a flight spell in Psi.

If you have the ability, ascending at all before you hit the ground should reduce fall damage, since if you move upwards, where you peak out is the new starting point for fall damage calculation. Its a trick I have to use with my Psi flight before getting slime boots in newer versions.

**Comment by Paindar** [comment]
Yes. I forgot to add codes. 
Now maybe you have to carry a bucket before you're going fly to sky by using Jet Engine.
I'm sorry, guys.
