### ISSUE TITLE
[Bug] World render corrupted after ability override (Only in some machines)

### ISSUE THREAD

**Issue by Paindar** [LambdaInnovation/AcademyCraft#711]
![qq 20190116221028](https://user-images.githubusercontent.com/16387007/51254221-8d42ac80-19db-11e9-9e44-0b1aac887979.jpg)

**Comment by Renniuq** [comment]
I'm getting the same issue, It happens both in LAN and Singleplayer. Seems to de-render all GUI, all non-opaque blocks, all blocks with more complicated models than a normal block (like the matrix core, chests, or solar panels, but not the metal former, node, or crafting table) and grass blocks. Based on that screenshot, it doesn't de-render fences, so it seems to be more complicated than just "non-block models". Also with water being de-rendered, but not lava, I'm more inclined to think transparency is a definite factor.

I'm not seeing any messages in the log when it happens.

forge 14.23.5.2808
I can provide a mod list if needed.

**Comment by Renniuq** [comment]
Just had it happen with just AcademyCraft-1.1.0_beta5, LambdaLib2-0.1.4, and Forge 14.23.5.2808 and no other mods - if its not happening for you, my best guess is its a hardware/driver issue. 

I just tested it on my friend's computer (the one hosting the LAN world) with just those same mods, same versions - no issue with overloading, leading me to further believe its hardware/driver based.

I'm using an integrated graphics card, my friend is not.

**Comment by SoulofSectonia** [comment]
Renniuq said it would be helpful for people who have this bug to upload there computer specs.
 So here they are:
Windows 8.1
Processor: Intel Celeron N2830 @ 2.16GHz 
RAM: 4.00 GB (3.89 GB usable)
Graphics: Intel HD Graphics
I hope that's everything. If not let me know.

**Comment by waddon1** [comment]
Also getting this issue
Specs:
Linux 4.20
Processor Intel i7 7700HQ @ 2.80GHZ
Ram: 16 GB
Graphics: Intel UHD Graphics

**Comment by Ruchian** [comment]
I thought [this](https://github.com/LambdaInnovation/AcademyCraft/issues/712) was related. I posted some information on my encounter with this issue there, but I'll elaberate it here.

Singleplayer/Servermultiplayer. It doesn't really matter. It doesn't matter which skill you use either, nor what ESP you obtain. The moment you hit "Overloaded", the world will start to corrupt and all menus are rendered invisible. In fact, you can't even see the main menu when exitting the world anymore. All you see is the corrupted view of the world you were last on.

![academycraft glitch](https://user-images.githubusercontent.com/24900404/53705240-3f66f400-3e23-11e9-9b79-e98e0b1541d9.png)

Specs:
Windows 8.1 Professional, 64x edition. (Tested multiple Java versions, so it doesn't matter which Java you use. I use Java 8. (1.8.0 Update 201)
Intel Core i7 4790K 4.00GHz (quadcore/hyperthreating) (8 logic cores)
Graphics: AMD R9 290 (this could be the cause, since AMD refuses to update drivers for windows 8.1 users, though considering intel graphics users have the same issue, I am now wondering about this.)
16GB RAM (allocated 6GB for minecraft client)
Usually launch minecraft through the Twitch Client
Tested and experienced it with Forge 14.23.5.2808, and Forge 14.23.5.2815 (minecraft 1.12.2 of course)
Sound: RealTek Audio
DirectX 11. 
MSI-7961 motherboard. (intel z97 chipset)
Screensize 1920x1080 though had minecraft run in 1600x900 Windowed Mode.
Minecraft runs from partition seperate from the OS system partition. (no raid)
Windows / everything (so far I know) is up to date.

Have fun figuring out what causes this. Also note me if you need more information.

**Comment by WeAthFoLD** [comment]
What's known so far:

1. This bug seems to be triggered by a various conditions, including **ability override, death when using teleporter ability, and opening ability developer UI**.
2. The bug never appears on NVIDIA cards, only AMD and Intel graphic cards.
3. A direct observation could say that face culling is set to the wrong value, but all the screenshots indicate that **some blocks' culling are correct while others are not**, so the problem might be more complicated than that.

**Comment by Ruchian** [comment]
What you also need to know is that this problem only exists in the 1.12.2 version (AcademyCraft 1.1.0 / LambdaLib2-0.1.7)

Here is what it looks like when I am trying to trigger this bug in Minecraft 1.7.10
![academycraft stillworking](https://user-images.githubusercontent.com/24900404/53799861-b42d5180-3f3b-11e9-8d16-4b630f12666b.png)

I suppose this is what should actually happen in 1.12.2 as well.

**Comment by WeAthFoLD** [comment]
Fixed. Takeaway: Restore texture state after changing them for GL_TEXTURE4 channel. (It is being used by MC itself in 1.12)
