### ISSUE TITLE
[Bug] 1.1.1 - Cannot be Downloaded via Twitch App

### ISSUE THREAD

**Issue by HalestormXV** [LambdaInnovation/AcademyCraft#782]
Your latest version of AcademyCraft 1.1.1 as well as the update to LamdaLib causes twitch to be unable to download it wtih "Cannot find addon dependency 316472"

This has been confirmed with only the 1.1.1 Update. As 1.1.0 downloads from the TwitchApp just fine.

**Comment by Ruchian** [comment]
In #773, this issue was mentioned. After some tests we discovered that this issue only happens with AcademyCraft 1.1.1 and only if you try to import a modpack. If you manually add the mod through the twitch client (by using "Get more content") Twitch will download the mod just fine.

I never had the issue myself, at least it never mentioned what dependancy was missing, but in the other threat I believed it was a Twitch issue. Currently I only partly do. It is likely a confusion on Twitch's part, since the mod supports Catserver as a plugin. Still, Catserver is not on the Curse Network, so it shouldn't even have a number.

If you remove AcademyCraft from the Profile and export it, (even when the profile has LambdaLib2), then the modpack will import. You'd need to instruct whoever you send the profile to to manually add AcademyCraft to the mods folder to fix the issue.

**Comment by nirvanaxiao6** [comment]
I'd like to know what is Twitch App and what can the app do. In mainland China, some websites are blocked so they are almost unknown for us.

**Comment by Ruchian** [comment]
The Twitch App, or Twitch Client (https://www.curseforge.com/twitch-client) is basically the successor of the Curse Client.
(windows version: https://desktop.twitchsvc.net/installer/windows/TwitchSetup.exe)
(You'd need a Twitch Account to log in, I assume Twitch.tv is blocked in China, but according to websites, you should be able to download the client app at least without VPN.)

Like the old Curse Client, the Twitch Client has access to the Curse network, allowing it to look up and download every minecraft mod, as well as download and install whole modpacks.

![afbeelding](https://user-images.githubusercontent.com/24900404/56208988-c3331380-6052-11e9-8e64-61118fc19253.png)

It seems to support mandarin.
![afbeelding](https://user-images.githubusercontent.com/24900404/56209035-d940d400-6052-11e9-8809-0c33d8fcca7f.png)

Instant mod searching on the Curse network.
![afbeelding](https://user-images.githubusercontent.com/24900404/56209141-173df800-6053-11e9-995f-2244b5298729.png)

When downloading a mod, it will also download an install the required dependancies (for example, when you install AcademyCraft 1.1.1, it will automatically look up and download LambdaLib2 with the correct version for you).

Aside from mods and modpacks, it can also download resourcepacks and world saves.

For modpacks it uses a small profile instance zip file, which holds a list of where to download what mod and all the configs for the said pack. This way, the file size remains small and since it will download mods at  their original location, the mod owner will still see how many times their mod has been downloaded.

It know when a new version has been uploaded to the Curse network and can also help update those mods with a single click.

You can obviously create (and upload if you want) modpacks yourself with it. You can make one with AcademyCraft 1.1.1 without noticing anything odd, but when you try to Import the said modpack (and let Twitch find and download the mods,) that is when this error occurs. It for some reason starts to look for a dependancy mod that is not on the Curse network, a mod called Catserver. (it thinks this is a mod on the Curse network (curseforge).)

This problem oddly did not happen with AcademyCraft 1.1.0. If you import a modpack profile with AcademyCraft 1.1.0, it will download the correct LambdaLib2 and work without problems.

Curse was at some point bought by Amazon. Amazon already aquired Twitch and Amazon then decided to combine Twitch and Curse.
Twitch was originally a service that allowed users to Live Stream videos (and upload videos), people could chat along and donate to the Streamer. In other words, for just launching Minecraft with mods, it's stuffed with bloated features you don't want or need. (Friendslist, videos and streaming features, advertisement (if you don't disable that) )

If something is not working on the Twitch Client, you can report it here:
https://help.twitch.tv/s/contactsupport?language=en_US

Update 16-04: 
Although I was thinking about reporting the issue considering this, it seems I myself no longer encounter the issue. I think Twitch fixed the issue without telling us in one of their random updates. (which makes me more certain that it is the Twitch Client who is causing this issue.)

People who are still encountering dependancy issues with modpacks that have academycraft, try test import a modpack today.

**Comment by nirvanaxiao6** [comment]
Thanks for your introduction! I will check it later and report the result to our leader.

**Comment by HalestormXV** [comment]
I will check this out later today as well. I spoke with the Powers at Be on both the Curse Side and Twitch Side of the App and brought this to their attention a few days ago as it seemed like something on their site (Twitch App wise) was calling to 316472 which no longer exists on the platform (it did at one time if you check a cached version of CurseForge which the TwitchApp pulls from) and explained to them how to replicate the issue. I know Twitch did a few hotfixes over these past couple of days and if @Ruchian has given this a test recently and it now seems to be working, hopefully that means they fixed it. I have yet to try with Uploading one of my modpacks and then having it approved and then having the app pull the modpack though. But I will most certainly edit this post with an update once I get home to test it via CurseForge and the TwitchApp platforms.
