### ISSUE TITLE
[Bug] Crash on loading a map.

### ISSUE THREAD

**Issue by ExerciseBook** [LambdaInnovation/AcademyCraft#802]
**Describe the bug**
Crash on loading a map.

**To Reproduce**
Enter a world.

**Expected behavior**
Load and play the game.

**Screenshots**
没有

**Desktop (please complete the following information):**
```
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.5
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2444693208 bytes (2331 MB) / 3539992576 bytes (3376 MB) up to 6392119296 bytes (6096 MB)
	JVM Flags: 10 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx6096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 63 mods loaded, 63 mods active
```

**Additional context**
https://github.com/LambdaInnovation/AcademyCraft/files/3315273/crash-2019-06-21_00.23.28-client.1.txt

**Comment by ExerciseBook** [comment]
不知道这个bug是什么原因
如果这个bug真的是都市学园mod造成的话希望可以早日修复 我想玩 ❤

**Comment by nirvanaxiao6** [comment]
是由于你的OpenGL版本过低导致的，这一问题一般出现在使用核显启动的电脑上，请切换为独显。（百度有教程）

**Comment by voidcl** [comment]
@ExerciseBook AC 1.12 版本以后openGL换成了3以上,但是Mac系统openGL默认为2.1,mc暂不支持core file引入来提升openGL版本,所以Mac系统暂不支持AC 1.12

**Comment by Ruchian** [comment]
@voidcl refering to: [LambdaLib2/issues/5](https://github.com/LambdaInnovation/LambdaLib2/issues/5)
According to the links posted by rlf23240
[stackoverflow.com/questions/19865463/opengl-4-1-under-mavericks](https://stackoverflow.com/questions/19865463/opengl-4-1-under-mavericks?lq=1)
[stackoverflow.com/questions/38164908/opengl-3-3-on-mac-osx-el-capitan-with-lwjgl](https://stackoverflow.com/questions/38164908/opengl-3-3-on-mac-osx-el-capitan-with-lwjgl)
making MacOS use OpenGL 3.3 or higher should be possible.

**Comment by voidcl** [comment]
@Ruchian We already know that we can use higher openGL version with core profile , actually , my old dev env is Mac too . But we can't use this way in MC develop  , because the core profile should be inited before the mc's window created and that's the problem is, we couldn't insert code into the mc original source code . If one day ,  forge provide us new interfaces or MC become open source , we can use the way you mentioned . Of course , if someone in our group can use Metal to refactor the shader , you will see the AC for Mac . But now , sorry :( .
(I bought a new win pc to code.)

**Comment by Ruchian** [comment]
I see, thanks for the answer. :+1: 
(I suspected as much before to be honest, but I feel like I had to mention it.) I am pretty sure others would have asked at some point.

Have fun with your new PC. :)

**Comment by Ruchian** [comment]
@voidcl , @ExerciseBook 

Just sharing information.

I asked the community of Forge about it. According to them, a lot of Minecraft runs on OpenGL 2.1 (or lower) code. Setting the core profile to 3.3 or higher would mean disabling legacy OpenGL features. Because of this they do not recommend using newer OpenGL.

At any rate, I conclude that it is likely not possible to get OpenGL 3.3+ to work on Mac OS without heavily modifying Minecraft from its core. I haven't gotten a reply on whether or not Forge supports modifying the OpenGL version (or will implement this feature) as of yet however. All they did say is that `` Mods should not be requiring higher versions`` of OpenGL instead.

Read it [here](https://www.minecraftforge.net/forum/topic/72098-1122-question-opengl-33-in-mac-os-x-1014-and-above/?do=findComment&comment=347915) if you want.
@rlf23240 (you may be interested in this as well)

Perhaps it is possible to have some sort of fall back in case GLSL 330 code doesn't work, but Weathfold already said [here](https://github.com/LambdaInnovation/AcademyCraft/issues/796#issuecomment-492900496):
> 
> 
> AcademyCraft does not and will not support MacOS, unless MacOS starts supporting using modern OpenGL features in compatibility profile.

**Comment by voidcl** [comment]
@Ruchian Roger that , thanks for your help to ask forge developers , Weathfold is the leader of Lambda Innovation , as well as he is the one who writen the shader (at least now , the other active programmers can't use GL script ), but he don't like Metal . So , AC will probably not support to Mac long time .
    As I say , If one day , someone is interested in Metal( like me 😄 ) or can use 2.1 GL to refactor shader part , the AC for Mac will be published . This is not an official reply , just I hope that . But , we have our own work . For example , I am a Java EE engineer at work so it's hard to me to spend my free time on learning computer graphics . So it will be an "idea" not a "feature" or a "bug" ,  that's all. .


  OK, I confess , NO GAME NO LIFE , I LIKE PLAYING GAMES!!!!!!!!!!!!!!!💃💃💃💃💃💃💃💃

   ( whisper ) : if you have a playstation account , be a friend ? No , I never played other games except Blizzards' on pc.

**Comment by ExerciseBook** [comment]
Thank you all. 🌹
