### ISSUE TITLE
Add new categories and abilities to academy craft  

### ISSUE THREAD

**Issue by K-Mind-TGFY** [LambdaInnovation/AcademyCraft#838]
I feel like adding new categories to academy craft would create more diversity in servers and such.

I understand that sticking to the categories from rail-gun would be ideal(I also know that there aren't a lot of level 5s in rail-gun). I believe that if you were going to make simple little categories with easy enough concepts and themes to it, like a pyrokinesis category or a new category which could be ice related. Mind out would be a nice one as well as arrow hand but those categories are harder to think of ability wise. Anyway I just think having more categories would be cool and creative

[Idea]

**Comment by K-Mind-TGFY** [comment]
> I feel like adding new categories to academy craft would create more diversity in servers and such.
> 
> I understand that sticking to the categories from rail-gun would be ideal(I also know that there aren't a lot of level 5s in rail-gun). I believe that if you were going to make simple little categories with easy enough concepts and themes to it, like a pyrokinesis category or a new category which could be ice related. Mind out would be a nice one as well as arrow hand but those categories are harder to think of ability wise. Anyway I just think having more categories would be cool and creative
> 
> [Idea]

**Comment by CarierxGroup** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"K-Mind-TGFY"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 中午11:45
收件人:&nbsp;"LambdaInnovation/AcademyCraft"<AcademyCraft@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [LambdaInnovation/AcademyCraft] Add new categories and abilities to academy craft   (#838)




Closed #838.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.







May i cloud forgot set to value
