### ISSUE TITLE
[Idea] Will this mod update to 1.16.5 and switch into Fabric?

### ISSUE THREAD

**Issue by misaka19465** [LambdaInnovation/AcademyCraft#882]
1.16有无计划进行开发，有的话何时开发，使用Fabric还是Forge

**Comment by KamiSami** [comment]
I don't think this developer plans to update anymore unfortunately, as the dev of mod (weathfold) promised bugfix that never came either, which has been long time now ever since. This was said in their discord server at 15.12.2020. So i wouldn't recommend waiting for updates anymore unfortunately... And "if" by some chance they decided to take this mod under work again, i personally would prefer forge over fabric if my voice matters, since most mods are available on it than fabric.

**Comment by misaka19465** [comment]
I've checked the codes. This mod depend on IC2, which doesn't update to 1.16.5. So it is impossible now.
